port: 3210
python_venv: "C:/Projects/PP2025-ProWeb"
python_executable: "C:/Projects/PP2025-ProWeb/.venv/Scripts/python.exe"
python_script: "C:/Projects/PP2025-ProWeb/lib/service/scanPy"
storage_path: "C:/Projects/PP2025-ProWeb/storageJSONs"
log_path: "C:/Projects/PP2025-ProWeb/log/info.log"